### ISSUE TITLE
Import only imports armature and fails to produce any mesh.

### ISSUE THREAD

**Issue by Fantazilite** [johnzero7/XNALaraMesh#111]
I used to use this tool to import meshes extracted from a video game. It used to work just fine. Now, about a year later, I get the following error when attempting to import a .ascii mesh, and it only produces an armature without any objects.

`Traceback (most recent call last):
  File "C:\Users\Funtazilite\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh\xps_tools.py", line 164, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "C:\Users\Funtazilite\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 78, in getInputFilename
    status = xpsImport()
  File "C:\Users\Funtazilite\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 159, in xpsImport
    meshes_obs = importMeshesList(armature_ob)
  File "C:\Users\Funtazilite\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 477, in importMeshesList
    importedMeshes = [importMesh(armature_ob, meshInfo)
  File "C:\Users\Funtazilite\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 477, in <listcomp>
    importedMeshes = [importMesh(armature_ob, meshInfo)
  File "C:\Users\Funtazilite\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 624, in importMesh
    makeBoneGroups(armature_ob, mesh_ob)
  File "C:\Users\Funtazilite\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\XNALaraMesh\import_xnalara_model.py", line 763, in makeBoneGroups
    boneGroup = armature_ob.pose.bone_groups.new(name=mesh_ob.name)
AttributeError: 'Pose' object has no attribute 'bone_groups'`

**Comment by Fantazilite** [comment]
Guess it just doesn't work on 4.0. My bad.
